//decisions
#include "Decisions\AmmoCheck.h"
#include "Decisions\DisregardsSafety.h"
#include "Decisions\EnemiesInRange.h"
#include "Decisions\EnemyPresense.h"
#include "Decisions\FeelsInDanger.h"
#include "Decisions\HasCooperativeTeammates.h"
#include "Decisions\IsInCover.h"
#include "Decisions\IsUnderLowThreat.h"
#include "Decisions\NearbyCombatCover.h"
#include "Decisions\ShouldMoveInForKill.h"

//decision actions
#include "Decisions\DecidedActions\BeginPatrolling.h"
#include "Decisions\DecidedActions\EngageEnemies.h"
#include "Decisions\DecidedActions\FallBack.h"
#include "Decisions\DecidedActions\FindNearCombatCover.h"
#include "Decisions\DecidedActions\MoveToEngage.h"
#include "Decisions\DecidedActions\MoveToSafePlace.h"
#include "Decisions\DecidedActions\ReloadWeapon.h"
#include "Decisions\DecidedActions\SinglePatrol.h"
#include "Decisions\DecidedActions\SuppressEnemies.h"